#!/bin/sh
set -euo pipefail

RED=$(tput setaf 1)
NO_COLOR=$(tput sgr0)

bundle exec rspec
if [[ $? != 0 ]]; then
  cat <<EOL >&2
    $RED
    FailingTestsError:
      In order to avoid broken commits in the history, all the tests must pass.
      Because of this, your changes will not be pushed until all errors are fixed.
      Afterwards, try pushing again.
    $NO_COLOR
EOL

  exit 1
fi

exit 0
